### ISSUE TITLE
At 1249 7/8 I'm getting Prime engrams at 1250, not 1252

### ISSUE THREAD

**Issue by imax9000** [andyschott/MaxPowerLevel#10]
![image](https://user-images.githubusercontent.com/654649/101097197-ae551c00-35b8-11eb-970e-148e3595a9c3.png)
![image](https://user-images.githubusercontent.com/654649/101097219-b8771a80-35b8-11eb-8a4f-9ef2aabdfb85.png)

**Comment by andyschott** [comment]
Good find! I'll get that fixed.

**Comment by andyschott** [comment]
This was fixed by ee0cfa60a5d438f9ce4367fd76201094795db4ad.
