### ISSUE TITLE
Base power is incorrectly calculated when exotics are highest in multiple armor slots

### ISSUE THREAD

**Issue by imax9000** [andyschott/MaxPowerLevel#5]
![image](https://user-images.githubusercontent.com/654649/87228879-19991a00-c39c-11ea-9b7b-0d4a1d1455d6.png)

My highest helmet is actually One-Eyed Mask @ 1031. And prismatic recaster is giving me 1032 engrams, not 1031.

It seems that in-game base power calculation ignores "only one exotic" rule, at least for armor. Can't confirm if it works the same for weapons.

**Comment by andyschott** [comment]
The Umbral engrams are strange - not sure we can rely on them to determine what the game things your max base power level is. It looks like Fail safe is dropping items at power level right now (at least as of your screenshot) - can you try to buy an engram from her and see what power level it is?

**Comment by imax9000** [comment]
Not at the moment, I've got more drops such that destiny2utils.com now shows my base power as 1032. I'll try to check again, if I end up in similar situation at higher levels.

But a few days ago, when Zavala and Banshee-44 were giving high level engrams, they had +1 level to what destiny2utils.com was showing. So I'm reasonably sure that Prismatic Recaster is not off here.

**Comment by andyschott** [comment]
That sure does make it sounds like they're allowing exotics in multiple slots. I'll see if I can try to recreate it on an alt as well.

**Comment by andyschott** [comment]
I was just able to recreate this. I had exotic armor as the highest item in two of my slots. If both exotics are counted, my base power level would be 1039, while the site said it is 1038. I redeemed a vendor engram from Failsafe (who is still dropping high), and it was at 1039.

I feel like this is a Bungie bug, but I'll update the site to ignore the single exotic rule. I'll assume that weapons work the same way, but I can't as easily verify that.

**Comment by doktor5000** [comment]
Seems this also applies, if an exotic is the highest in a given slot. Saw this already 2 times, currently have this issue on my titan. Lowest item in helmet slot displayed is a dreambane helm with 1058, but I've got a khepri's horn with 1059 in my inventory.
Problem seems to be that something seems to consider my dunemarchers with 1060 as the second exotic, even when I've got dreambane greaves with 1060, the exotic seems to be preferred for whatever reason.

**Comment by andyschott** [comment]
Currently the site uses logic where if there are two exotics that are the highest in the slot, it will use the exotic where the highest legendary is lower. For example, if your highest non-exotic boots are 1057, then it's better to use Dunemarchers over Khepri's Horn since that would result in a higher overall power level.

I have this fixed locally so that the site will use the highest item in each slot and not check for exotics. I hope to get this deployed sometime today.

**Comment by imax9000** [comment]
> it will use the exotic where the highest legendary is lower

I don't think it actually works this way :( This might be a bug.

![image](https://user-images.githubusercontent.com/654649/87252020-cf7d6a80-c467-11ea-80d0-92ff53f329cc.png)
![image](https://user-images.githubusercontent.com/654649/87252035-e9b74880-c467-11ea-910f-663f2d2e031c.png)

Notice that it picked up 960 legendary helmet, while there's a legendary 1032 chest piece.

If it's checking level of legendary items only when exotics have equal level - then it's doing it wrong :) AFAIU, in order to maximize power level under "only one exotic" rule it would need to pick exotic in a slot with the largest *difference* between exotic and next non-exotic.

**Comment by doktor5000** [comment]
In your case, the 1033 exotic chest piece is higher, so it seems to pick that up instead. Then it seems to ignore the 2 higher exotics for the helmet, as those are also exotics.

For comparison, this is my case: 1058 helmet as lowest, and it prefers 1060 dunemarchers as highest for the legs.

![d2utils_1](https://user-images.githubusercontent.com/7667040/87253203-8a623400-c479-11ea-9ad2-43afb0bd9e23.PNG)

Whereas I do have a 1059 exotic helmet, and 1060 legendary boots:

![d2utils_2](https://user-images.githubusercontent.com/7667040/87253235-dca35500-c479-11ea-9a7e-54f8ead77699.PNG)

FWIW, base power calculation doesn't differ that much in my case, DIM says 1059.6 whereas destinyutils says 1059 1/2.

I'd say relax the "one exotic" rule, and also always prefer a legendary piece if it's the highest and an equal-level exotic is also avilable in that same slot.

**Comment by andyschott** [comment]
It does sound like there are some bugs with the power level calculation and exotics. Of course once I remove the exotic check none of this will matter - it will always use the highest available in each slot.

If/when Bungie reverts this so their check does take the one exotic rule into account, I'll keep these cases in mind and try to fix the bugs.

**Comment by andyschott** [comment]
I just deployed a changed so that the site now always uses whatever item is highest in each slot - it doesn't do any special checks for exotics. As I said, I'll keep your items in mind if/when Bungie changes the game to go back to only using 1 exotic when calculating max power.

**Comment by andyschott** [comment]
Fixed by 9bc83cebd6000b91829ecb01e6f17158db7be970.

**Comment by doktor5000** [comment]
Thanks for the quick fix :)
