### ISSUE TITLE
Formatting issue on iPhone

### ISSUE THREAD

**Issue by bill0042** [andyschott/MaxPowerLevel#7]
I hope this is the right place. For several days I have been having display formatting issues (image attached) that never happened before. I am using Safari on an iPhone 11 pro max with iOS 13.5. BTW, this is an awesomely useful and unique tool. Many thanks for making it.
![0BE9D2D2-B060-4B4A-93B1-A15B521A58BA](https://user-images.githubusercontent.com/68356139/87608087-de585d00-c6b3-11ea-8fcd-461476e15ea9.png)

**Comment by andyschott** [comment]
Yep, this is the right place. I've noticed that too, but haven't had a chance to fix it yet. Thanks for reporting the issue!

**Comment by andyschott** [comment]
@bill0042 I was planning on fixing this today, but when I load the site on my phone now everything is rendering correctly. I wonder if it was a caching issue, and the CSS from the previous design was hanging around or something. Are you still able to recreate this? If so, can you try clearing the cache on your phone and see if that fixes it for you?

**Comment by bill0042** [comment]
Yes, clearing the cache did resolve the issue. Should I close the issue or is there something you can do to force the cached content to be updated so others won't have the issue? Also, is there a way to offer suggestions for the site? Thanks again for all your efforts!

**Comment by andyschott** [comment]
I'm not aware of any automatic way of clearing the cache unfortunately. I didn't manually clear the cache on my phone, and it fixed itself - so hopefully either now or soon it should work correctly for everyone.

You can close this issue, since it's working for you.

If you have any other suggestions or find any bugs, please open an issue here and I'll look into it. I'm glad that you find the site useful!

**Comment by bill0042** [comment]
I'll close it, but I did some searching and others suggest changing the name of the css file when it changes either manually or using some method to append a version number. Not a big deal, though. Thanks again!
